"""Schema updates

Revision ID: a53e06507a9d
Revises: 
Create Date: 2026-09-19 15:00:54.821167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53e06507a9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('deduplication_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('failure_details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deduplication_key')
    )
    op.create_table('timelines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('initialization_ref', sa.String(), nullable=False),
    sa.Column('n_accepted', sa.BigInteger(), nullable=False),
    sa.Column('t_trained', sa.BigInteger(), nullable=False),
    sa.Column('e_indexed', sa.BigInteger(), nullable=False),
    sa.Column('active_runtime', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkpoints',
    sa.Column('timeline_id', sa.String(), nullable=False),
    sa.Column('age', sa.BigInteger(), nullable=False),
    sa.Column('file_manifest', sa.JSON(), nullable=False),
    sa.Column('logical_digest', sa.String(), nullable=False),
    sa.Column('artifact_checksums', sa.JSON(), nullable=False),
    sa.Column('runtime_reference', sa.String(), nullable=False),
    sa.Column('retention_role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('timeline_id', 'age')
    )
    op.create_table('games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timeline_id', sa.String(), nullable=False),
    sa.Column('visitor_color', sa.String(), nullable=False),
    sa.Column('pinned_age', sa.BigInteger(), nullable=False),
    sa.Column('runtime_digest', sa.String(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('termination', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('public_share_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_share_id')
    )
    op.create_table('training_steps',
    sa.Column('timeline_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('parent_digest', sa.String(), nullable=False),
    sa.Column('output_digest', sa.String(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('replay_manifest', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('publication_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('timeline_id', 'sequence')
    )
    op.create_table('experience_events',
    sa.Column('timeline_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('trajectory_digest', sa.String(), nullable=False),
    sa.Column('acceptance_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('uci', sa.String(), nullable=False),
    sa.Column('san', sa.String(), nullable=False),
    sa.Column('state_hash', sa.String(), nullable=False),
    sa.Column('prefix_key', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('experience_events')
    op.drop_table('training_steps')
    op.drop_table('games')
    op.drop_table('checkpoints')
    op.drop_table('timelines')
    op.drop_table('jobs')
    # ### end Alembic commands ###
